### ISSUE TITLE
RQT Image View Plugin Won't Load

### ISSUE THREAD

**Issue by paralin** [ros/ros-overlay#138]
```
ERROR] [1501718751.026417745]: Failed to load nodelet [rqt_image_view/ImageView_1] of type [rqt_image_view/ImageView]
: Failed to load library /opt/ros/lunar/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT
_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could n
ot load library (Poco exception = libopencv_core3.so.3.2: cannot open shared object file: No such file or directory) 
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could
 not load plugin "rqt_image_view/ImageView"                                                                          
```

The file is present at /opt/ros/lunar/lib//librqt_image_view.so, but since there's an extra slash in that path (I think?) it's not loading the library correctly. I think there's a path issue somewhere in the overlay.

I've tried:

 - Rebuilding ros-lunar/opencv3 and ros-lunar/rqt and ros-linar/rqt_image_view
 - Deleting ~/.config/ros.org

**Comment by allenh1** [comment]
> The file is present at /opt/ros/lunar/lib//librqt_image_view.so, but since there's an extra slash in that path (I think?) it's not loading the library correctly

This could indeed be the culprit. There's likely an issue with one of the `.cmake` files that is installed by `image_view`, or there's some sort of `lib64` problem (Ubuntu only has `lib`, so some packages just assume things are in lib).

A patch should fix this right up, after the correct file is found.

**Comment by paralin** [comment]
image_view doesn't work either:

```
/opt/ros/lunar/lib/image_view/image_view: error while loading shared libraries: libopencv_core3.so.3.2: ca
```

I've rebuilt opencv3 (from ros-lunar) a few times, still can't find it.

**Comment by allenh1** [comment]
@paralin I had a few to investigate it now, and it seems that the `libopencv_core*.so` files end up in `/opt/ros/lunar/lib64`, and the image view files end up in `/opt/ros/lunar/lib`.

When I get a few more, I'll try and figure out why. 

In the mean time, you can get things running by just doing this:

```
allenh1@hunter-laptop /opt/ros/lunar/share $ export LD_LIBRARY_PATH="/opt/ros/lunar/lib64:${LD_LIBRARY_PATH}" 
allenh1@hunter-laptop /opt/ros/lunar/share $ rosrun image_view image_view 
```

**Comment by allenh1** [comment]
@paralin Please 

```
emaint sync -r ros-overlay
```

then re-emerge `ros-lunar/catkin`. After that, you should be all set.

**Comment by pandyarohan** [comment]
This comment here fixed it for me with minimal effort: https://github.com/udacity/sdc-issue-reports/issues/1444#issuecomment-476022863

Basically you need to run the ROS setup script again:

`source /opt/ros/kinetic/setup.bash`

**Comment by brennanpeter** [comment]
Not sure if this is the right place, but I'm running into something similar issue on Ubuntu 20.04 and Ros Noetic

```
[ERROR] [1596418614.987326439]: Failed to load nodelet [rqt_image_view/ImageView_1] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/noetic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block)
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
```
I get this error after running rqt and trying to launch Image View

**Comment by raysworld** [comment]
> Not sure if this is the right place, but I'm running into something similar issue on Ubuntu 20.04 and Ros Noetic
> 
> ```
> [ERROR] [1596418614.987326439]: Failed to load nodelet [rqt_image_view/ImageView_1] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/noetic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block)
> RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
> PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
> ```
> 
> I get this error after running rqt and trying to launch Image View

I got the same error on Ubuntu 20.04 and ROS noetic

**Comment by csabato-6river** [comment]
➕ 1 here, also seeing this on Ubuntu 20.04 and ROS noetic
`[ERROR] [1596554090.402955185]: Failed to load nodelet [rqt_image_view/ImageView_0] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/noetic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block)
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
terminate called after throwing an instance of 'boost::wrapexcept<boost::lock_error>'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
`

**Comment by allenh1** [comment]
@brennanpeter / @raysworld / @csabato-6river Please report this upstream [here](https://github.com/ros-visualization/rqt_image_view), as this repository is for Gentoo Linux releases.

It actually looks like this could be ros-visualization/rqt_image_view#37

**Comment by dvillevald** [comment]
I am having a similar error on Ubuntu 18.04:

**$ rqt_image_view /rgb_camera/image_raw**

[ERROR] [1609309685.178914800]: Failed to load nodelet [rqt_image_view/ImageView_0] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/melodic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libpng12.so.0: cannot open shared object file: No such file or directory)
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
pure virtual method called
terminate called recursively
Aborted (core dumped)

Appreciate any suggestions.

**Comment by allenh1** [comment]
> I am having a similar error on Ubuntu 18.04:

@dvillevald Again, this repository is for Gentoo, but I can try and help you figure things out. In your case, it looks like you cannot find `libpng12.so.0`. On ubuntu, this should be the package `libpng12-0`. If that package is installed, check that you can find `libpng12.so.0` in one element of your `$LD_LIBRARY_PATH` variable.

You should see it in the output of this command:
```
for i in ${LD_LIBRARY_PATH//:/ } /usr/lib; do find $i -name "libpng12*"; done
```

**Comment by nhjydywd** [comment]
I think the issue may have some relations with `mysql`. 
I met the same problem, and I solved the problem with:
`sudo apt purge mysql-*`
`sudo apt purge ros-noetic-*`
`sudo apt install ros-noetic-desktop-full`
Now my `rqt_image_view` just worked again.

**Comment by AhmettCelik1** [comment]
sudo apt-get install ros-noetic-rqt-image-view

sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

might help the two orders.

**Comment by leo038** [comment]
I resolved the problem by:
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtiff.so.5
